import rpg as RPG
pocion_1 = RPG.Pocion(nombre="Pocion 1", descripcion="Restaura la salud del personaje", tipo="salud", nivel=2)
personaje_1 = RPG.Personaje(nombre="Juanito", salud=100,energia=60,ataque_basico=25,habilidades=[],inventario=[])
enemigo_1 = RPG.Enemigo(nombre="Ogro", salud=75, energia=20, ataque_basico=15, experiencia=40, drop=pocion_1)
habilidad_1 = RPG.Habilidad(nombre="Llamarada", ataque=30, energia_requerida=10)
personaje_1.aprender_habilidad(habilidad_1)

personaje_1.atacar(enemigo_1)
personaje_1.atacar(enemigo_1)
personaje_1.atacar(enemigo_1)

enemigo_2 = RPG.Enemigo(nombre="Lobo", salud=100, energia=20, ataque_basico=15, experiencia=40,drop=None)
enemigo_2.atacar(personaje_1)
personaje_1.usar_habilidad(habilidad_1,enemigo_2)
personaje_1.atacar(enemigo_2)
personaje_1.atacar(enemigo_2)
personaje_1.usar_habilidad(habilidad_1,enemigo_2)
personaje_1.tomar_pocion(pocion_1)
habilidad_2 = RPG.Habilidad(nombre="Hielo", ataque=20, energia_requerida=5)
personaje_1.aprender_habilidad(habilidad_2)
habilidad_3 = RPG.Habilidad(nombre="Terremoto", ataque=50, energia_requerida=25)
personaje_1.aprender_habilidad(habilidad_3)
habilidad_4 = RPG.Habilidad(nombre="Semilla", ataque=5, energia_requerida=1)
personaje_1.aprender_habilidad(habilidad_4)
personaje_1.olvidar_habilidad(habilidad_2)
personaje_1.aprender_habilidad(habilidad_4)
personaje_1.descansar()
personaje_1.olvidar_habilidad(habilidad_2)
personaje_1.tomar_pocion(pocion_1)

objeto_1= RPG.Objeto(nombre="Palo", descripcion="Un palo comun y corriente")
personaje_1.agregar_objeto(objeto_1)
print(objeto_1.descripcion)
objeto_2= RPG.Objeto(nombre="Espada", descripcion="Una espada de metal")
personaje_1.agregar_objeto(objeto_2)
personaje_1.eliminar_objeto(objeto_1)
objeto_3= RPG.Objeto(nombre="Escudo", descripcion="Un escudo de madera")
personaje_1.eliminar_objeto(objeto_3)

personaje_2 = RPG.Personaje(nombre="Pedrito", salud=150,energia=50,ataque_basico=20,habilidades=[],inventario=[])
personaje_2.aprender_habilidad(habilidad_4)
personaje_2.aprender_habilidad(habilidad_2)
personaje_2.usar_habilidad(habilidad_2,personaje_1)
personaje_1.usar_habilidad(habilidad_3,personaje_2)
personaje_2.atacar(personaje_1)
personaje_2.usar_habilidad(habilidad_2,personaje_1)
personaje_2.usar_habilidad(habilidad_2,personaje_1)
personaje_2.usar_habilidad(habilidad_2,personaje_1)
personaje_1.atacar(personaje_1)
personaje_2.atacar(personaje_1)
